#pragma once
#include <iostream>
#include <string>
#include <list>
#include "functions.h"
#include "Operator.h"
#include "Storage.h"
#include "Compiler.h"
#include "Context.h"
#include "State.h"
#include "DecreaseIndex.h"
#include "IncreaseIndex.h"
#include "DecreaseValue.h"
#include "IncreaseValue.h"
#include "OpenLoopBracket.h"
#include "ShowCharacter.h"
#include "StateCompiled.h"
#include "StateNonCompiled.h"
#include "StateRunning.h"
#include <exception>
#include <typeinfo>
using namespace std;